control-plane:
  host: "0.0.0.0"
  port: 9000
  workers: 1
  gc_interval: 60
  runner_image: "localhost/golem-runner:v1"

llm:
  provider: "watsonx"
  protocol: "watsonx"
  model: "openai/gpt-oss-120b"
  project_id: "9def6989-c276-4042-8fc2-5b77a8e56ade"
  url: "https://us-south.ml.cloud.ibm.com"
