apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: golem-control-plane
  labels:
    app.kubernetes.io/part-of: golem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: golem-control-plane
subjects:
  - kind: ServiceAccount
    name: golem-control-plane
    namespace: golem-system
